;; 包丁を掴む．
(load "grasp-knife.l")

;; 切る．
(load "potato-cut-first-with-rec-tmp.l")
(now-cut)

;; ピーラーに持ち替える
(load "peeler-change.l")

;; 剥く
(load "potato-peel-ver3-first-with-rec-tmp.l")
(now-peel)
;; 剥く
(load "potato-peel-ver3-second-with-rec-tmp.l")
(now-peel)
;; 剥く
(load "potato-peel-ver3-second-with-rec-tmp.l")
(now-peel)
;; 剥く
(load "potato-peel-ver3-second-with-rec-tmp.l")
(now-test)


;; 包丁に持ち替える
(load "knife-change.l")


;; 切る．
(load "potato-cut-second-with-rec-tmp.l")
(now-cut)

;; ピーラーに持ち替える
(load "peeler-change.l")

;; 剥く
(load "potato-peel-ver3-first-with-rec-tmp.l")
(now-peel)
;; 剥く
(load "potato-peel-ver3-second-with-rec-tmp.l")
(now-peel)
;; 剥く
(load "potato-peel-ver3-second-with-rec-tmp.l")
(now-peel)
;; 剥く
(load "potato-peel-ver3-second-with-rec-tmp.l")
(now-test)

