;; 包丁を掴む．
(load "grasp-knife.l")

;; 切る．
(load "potato-cut-first.l")
(now-cut)

;; ピーラーに持ち替える
(load "peeler-change.l")

;; 剥く１
(load "potato-peel-ver2-first.l")
(now-peel)

;; 剥く２
(load "potato-peel-ver2-second.l")
(now-peel)
;; 剥く３
(load "potato-peel-ver2-second.l")
(now-peel)
;; 剥く４
(load "potato-peel-ver2-second.l")
(now-peel)
;; 剥く５
(load "potato-peel-ver2-second.l")
(now-peel)
;; 剥く６
(load "potato-peel-ver2-second.l")
(now-peel)
;; 剥く７
(load "potato-peel-ver2-second.l")
(now-peel)
;; 剥く８
(load "potato-peel-ver2-second.l")
(now-peel)
;; 剥く９
(load "potato-peel-ver2-second.l")
(now-peel)
;; 剥く１０
(load "potato-peel-ver2-second.l")
(now-peel)
;; 剥く１１
(load "potato-peel-ver2-second.l")
(now-peel)
;; 剥く１２
(load "potato-peel-ver2-second.l")
(now-test)


;; 包丁に持ち替える
(load "knife-change.l")


;; 切る．
(load "potato-cut-second.l")
(now-cut)

;; ピーラーに持ち替える
(load "peeler-change.l")


;; 剥く１
(load "potato-peel-ver2-first.l")
(now-peel)

;; 剥く２
(load "potato-peel-ver2-second.l")
(now-peel)
;; 剥く３
(load "potato-peel-ver2-second.l")
(now-peel)
;; 剥く４
(load "potato-peel-ver2-second.l")
(now-peel)
;; 剥く５
(load "potato-peel-ver2-second.l")
(now-peel)
;; 剥く６
(load "potato-peel-ver2-second.l")
(now-peel)
;; 剥く７
(load "potato-peel-ver2-second.l")
(now-peel)
;; 剥く８
(load "potato-peel-ver2-second.l")
(now-peel)
;; 剥く９
(load "potato-peel-ver2-second.l")
(now-peel)
;; 剥く１０
(load "potato-peel-ver2-second.l")
(now-peel)
;; 剥く１１
(load "potato-peel-ver2-second.l")
(now-peel)
;; 剥く１２
(load "potato-peel-ver2-second.l")
(now-test)
