;; 包丁を掴む．
(load "grasp-knife.l")

;; 切る．
(load "carrot-cut-first-with-rec-tmp.l")
(now-cut)

;; ピーラーに持ち替える
(load "peeler-change.l")

;; 剥く
(load "carrot-peel-first-with-rec-tmp.l")
(now-peel)
;; 剥く
(load "carrot-peel-first-with-rec-tmp.l")
(now-peel)
;; 剥く
(load "carrot-peel-first-with-rec-tmp.l")
(now-peel)
;; 剥く
(load "carrot-peel-first-with-rec-tmp.l")
(now-peel)
;; 剥く
(load "carrot-peel-first-with-rec-tmp.l")
(now-peel)
;; 剥く
(load "carrot-peel-first-with-rec-tmp.l")
(now-peel)
;; 剥く
(load "carrot-peel-first-with-rec-tmp.l")
(now-peel)
;; 剥く
(load "carrot-peel-first-with-rec-tmp.l")
(now-peel)
;; 剥く
(load "carrot-peel-first-with-rec-tmp.l")
(now-peel)
;; 剥く
(load "carrot-peel-first-with-rec-tmp.l")
(now-peel)
;; 剥く
(load "carrot-peel-first-with-rec-tmp.l")
(now-peel)
;; 剥く
(load "carrot-peel-first-with-rec-tmp.l")
(now-peel)



;; 包丁に持ち替える
(load "knife-change.l")


;; 切る．
(load "carrot-cut-second-with-rec-tmp.l")
(now-cut)

;; ピーラーに持ち替える
(load "peeler-change.l")

;; 剥く
(load "carrot-peel-first-with-rec-tmp.l")
(now-peel)
;; 剥く
(load "carrot-peel-first-with-rec-tmp.l")
(now-peel)
;; 剥く
(load "carrot-peel-first-with-rec-tmp.l")
(now-peel)
;; 剥く
(load "carrot-peel-first-with-rec-tmp.l")
(now-peel)
;; 剥く
(load "carrot-peel-first-with-rec-tmp.l")
(now-peel)
;; 剥く
(load "carrot-peel-first-with-rec-tmp.l")
(now-peel)
;; 剥く
(load "carrot-peel-first-with-rec-tmp.l")
(now-peel)
;; 剥く
(load "carrot-peel-first-with-rec-tmp.l")
(now-peel)
;; 剥く
(load "carrot-peel-first-with-rec-tmp.l")
(now-peel)
;; 剥く
(load "carrot-peel-first-with-rec-tmp.l")
(now-peel)
;; 剥く
(load "carrot-peel-first-with-rec-tmp.l")
(now-peel)
;; 剥く
(load "carrot-peel-first-with-rec-tmp.l")
(now-peel)
