;; 剥く
(load "potato-peel-ver2-first-with-rec-hor-tmp-test.l")
(now-peel)
;; 剥く
(load "potato-peel-ver2-first-with-rec-hor-tmp-test.l")
(now-peel)
;; 剥く
(load "potato-peel-ver2-first-with-rec-hor-tmp-test.l")
(now-peel)
;; 剥く
(load "potato-peel-ver2-first-with-rec-hor-tmp-test.l")
(now-peel)
;; 剥く
(load "potato-peel-ver2-first-with-rec-hor-tmp-test.l")
(now-peel)
;; 剥く
(load "potato-peel-ver2-first-with-rec-hor-tmp-test.l")
(now-peel)
;; 剥く
(load "potato-peel-ver2-first-with-rec-hor-tmp-test.l")
(now-peel)
;; 剥く
(load "potato-peel-ver2-first-with-rec-hor-tmp-test.l")
(now-peel)
;; 剥く
(load "potato-peel-ver2-first-with-rec-hor-tmp-test.l")
(now-peel)
;; 剥く
(load "potato-peel-ver2-first-with-rec-hor-tmp-test.l")
(now-peel)
;; 剥く
(load "potato-peel-ver2-first-with-rec-hor-tmp-test.l")
(now-peel)
;; 剥く
(load "potato-peel-ver2-first-with-rec-hor-tmp-test.l")
(now-peel)
;; 剥く
(load "potato-peel-ver2-first-with-rec-hor-tmp-test.l")
(now-peel)
;; 剥く
(load "potato-peel-ver2-first-with-rec-hor-tmp-test.l")
(now-peel)
;; 剥く
(load "potato-peel-ver2-first-with-rec-hor-tmp-test.l")
(now-peel)
;; 剥く
(load "potato-peel-ver2-first-with-rec-hor-tmp-test.l")
(now-peel)
;; 剥く
(load "potato-peel-ver2-first-with-rec-hor-tmp-test.l")
(now-peel)
;; 剥く
(load "potato-peel-ver2-first-with-rec-hor-tmp-test.l")
(now-peel)
