;; 包丁を掴む．
(load "grasp-knife.l")

;; 切る．
(load "potato-cut-first-with-rec-tmp-test.l")
(now-cut)

;; ピーラーに持ち替える
(load "peeler-change.l")

;; 剥く
(load "potato-peel-ver2-first-with-rec-hor-tmp-test.l")
(now-peel)

;; 剥く
(load "potato-peel-ver2-first-with-rec-hor-tmp-test.l")
(now-peel)
;; 剥く
(load "potato-peel-ver2-first-with-rec-hor-tmp-test.l")
(now-peel)
;; 剥く
(load "potato-peel-ver2-first-with-rec-hor-tmp-test.l")
(now-peel)
;; 剥く
(load "potato-peel-ver2-first-with-rec-hor-tmp-test.l")
(now-peel)
;; 剥く
(load "potato-peel-ver2-first-with-rec-hor-tmp-test.l")
(now-peel)
;; 剥く
(load "potato-peel-ver2-first-with-rec-hor-tmp-test.l")
(now-peel)
;; 剥く
(load "potato-peel-ver2-first-with-rec-hor-tmp-test.l")
(now-peel)
;; 剥く
(load "potato-peel-ver2-first-with-rec-hor-tmp-test.l")
(now-peel)
;; 剥く
(load "potato-peel-ver2-first-with-rec-hor-tmp-test.l")
(now-peel)
;; 剥く
(load "potato-peel-ver2-first-with-rec-hor-tmp-test.l")
(now-peel)
;; 剥く
(load "potato-peel-ver2-first-with-rec-hor-tmp-test.l")
(now-peel)
;; 剥く
(load "potato-peel-ver2-first-with-rec-hor-tmp-test.l")
(now-peel)
;; 剥く
(load "potato-peel-ver2-first-with-rec-hor-tmp-test.l")
(now-peel)
;; 剥く
(load "potato-peel-ver2-first-with-rec-hor-tmp-test.l")
(now-peel)
;; 剥く
(load "potato-peel-ver2-first-with-rec-hor-tmp-test.l")
(now-peel)
;; 剥く
(load "potato-peel-ver2-first-with-rec-hor-tmp-test.l")
(now-peel)
;; 剥く
(load "potato-peel-ver2-first-with-rec-hor-tmp-test.l")
(now-peel)
;; 剥く
(load "potato-peel-ver2-first-with-rec-hor-tmp-test.l")
(now-peel)
