;; 剥く
(load "potato-peel-ver2-first-with-rec-tmp.l")
(now-peel)
;; 剥く
(load "potato-peel-ver2-first-with-rec-tmp.l")
(now-peel)
;; 剥く
(load "potato-peel-ver2-first-with-rec-tmp.l")
(now-peel)
;; 剥く
(load "potato-peel-ver2-first-with-rec-tmp.l")
(now-peel)
;; 剥く
(load "potato-peel-ver2-first-with-rec-tmp.l")
(now-peel)
;; 剥く
(load "potato-peel-ver2-first-with-rec-tmp.l")
(now-peel)
;; 剥く
(load "potato-peel-ver2-first-with-rec-tmp.l")
(now-peel)
;; 剥く
(load "potato-peel-ver2-first-with-rec-tmp.l")
(now-peel)
;; 剥く
(load "potato-peel-ver2-first-with-rec-tmp.l")
(now-peel)
;; 剥く
(load "potato-peel-ver2-first-with-rec-tmp.l")
(now-peel)
;; 剥く
(load "potato-peel-ver2-first-with-rec-tmp.l")
(now-peel)
;; 剥く
(load "potato-peel-ver2-first-with-rec-tmp.l")
(now-peel)
